.PHONY: all image qemu clean help

all image qemu clean help:
	@$(MAKE) -f Makefile \
		PRODUCT_NAME="$(PRODUCT_NAME)" \
		FREEBSD_RELEASE="$(FREEBSD_RELEASE)" \
		FREEBSD_ARCH="$(FREEBSD_ARCH)" \
		FREEBSD_IMAGE_BASENAME="$(FREEBSD_IMAGE_BASENAME)" \
		BUILD_DIR="$(BUILD_DIR)" \
		OUTPUT_DIR="$(OUTPUT_DIR)" \
		$@
