[*]
in_terminal=0
show_hidden=0
sort=name;ascending;
view_mode=icon

[Install.desktop]
x=42
y=72

[LiveShell.desktop]
x=42
y=168

[Files.desktop]
x=42
y=264

[InstallerHelp.desktop]
x=42
y=360

[Reboot.desktop]
x=42
y=456
